#!/usr/bin/env bash
###############################################################################
# setup-control-panel.sh -- the ONLY way the read-write web control panel
# (control-panel.py) ever gets turned on. It is never enabled as a side
# effect of installing the platform or adding an instance -- an operator
# has to run this script and explicitly say so, the same opt-in shape as
# this platform's existing Discord-webhook prompt (blank/declined by
# default, nothing sent/exposed unless a value is actively supplied).
#
# What this does when enabling:
#   1. Generates a random 32-byte (64 hex char) admin token with
#      `openssl rand -hex 32` -- the same tool/strength this platform's
#      README already points to for anyone hand-generating a secret.
#   2. Writes GS_BASE/control-panel.conf (mode 600, root-owned) containing
#      CONTROL_PANEL_ENABLED, CONTROL_PANEL_TOKEN, CONTROL_PANEL_BIND,
#      CONTROL_PANEL_PORT.
#   3. Prints the token to the terminal EXACTLY ONCE. It is never logged,
#      never written anywhere else, and never retrievable again after this
#      -- only re-rotated (see --rotate below).
#   4. Installs and starts a systemd unit (gameserver-control-panel.service)
#      running control-panel.py as root, unless --no-systemd is given.
#
# Usage:
#   sudo ./setup-control-panel.sh --enable [-y] [--bind ADDR] [--port N]
#   sudo ./setup-control-panel.sh --disable
#   sudo ./setup-control-panel.sh --rotate
#   sudo ./setup-control-panel.sh              (interactive prompt)
#
# Every flag/env var below can be overridden for local testing without
# root or a real systemd -- see CONTROL_PANEL_GS_BASE and --no-systemd.
###############################################################################
set -uo pipefail

GS_BASE="${CONTROL_PANEL_GS_BASE:-/srv/gameservers}"
SCRIPTS_DIR="${GS_BASE}/scripts"
CONF_FILE="${GS_BASE}/control-panel.conf"
UNIT_FILE="/etc/systemd/system/gameserver-control-panel.service"

MODE=""            # "", "enable", "disable", "rotate"
ASSUME_YES=0
BIND="127.0.0.1"
PORT="8642"
NO_SYSTEMD=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --enable) MODE="enable" ;;
        --disable) MODE="disable" ;;
        --rotate) MODE="rotate" ;;
        -y|--yes) ASSUME_YES=1 ;;
        --bind) shift; BIND="${1:-127.0.0.1}" ;;
        --port) shift; PORT="${1:-8642}" ;;
        --no-systemd) NO_SYSTEMD=1 ;;
        -h|--help)
            grep '^#' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            exit 2
            ;;
    esac
    shift
done

log()  { echo "[control-panel-setup] $*"; }
warn() { echo "[control-panel-setup] WARNING: $*" >&2; }
die()  { echo "[control-panel-setup] ERROR: $*" >&2; exit 1; }

require_root_unless_test() {
    # Real installs must run as root: this writes root-owned files under
    # GS_BASE and (optionally) a systemd unit. CONTROL_PANEL_GS_BASE being
    # set is the same signal used across this feature's other scripts to
    # mean "this is a test sandbox, not a real host" -- when it's set,
    # root is not required so tests/control_panel_test.sh can exercise
    # this script's real logic without needing real root.
    if [[ "${EUID}" -ne 0 && -z "${CONTROL_PANEL_GS_BASE:-}" ]]; then
        die "must run as root (sudo). Re-run: sudo $0 ${*}"
    fi
}

read_current_conf() {
    CUR_ENABLED="0"; CUR_TOKEN=""; CUR_BIND="$BIND"; CUR_PORT="$PORT"
    [[ -f "$CONF_FILE" ]] || return 0
    # shellcheck disable=SC1090
    source <(grep -E '^(CONTROL_PANEL_ENABLED|CONTROL_PANEL_TOKEN|CONTROL_PANEL_BIND|CONTROL_PANEL_PORT)=' "$CONF_FILE" 2>/dev/null || true)
    CUR_ENABLED="${CONTROL_PANEL_ENABLED:-0}"
    CUR_TOKEN="${CONTROL_PANEL_TOKEN:-}"
    CUR_BIND="${CONTROL_PANEL_BIND:-$BIND}"
    CUR_PORT="${CONTROL_PANEL_PORT:-$PORT}"
}

write_conf() {
    local enabled="$1" token="$2" bind="$3" port="$4"
    mkdir -p "$GS_BASE"
    umask 077
    {
        echo "# control-panel.conf -- generated by setup-control-panel.sh on $(date '+%Y-%m-%d %H:%M:%S')"
        echo "# This file gates the read-write web control panel. CONTROL_PANEL_TOKEN is a"
        echo "# live admin credential -- treat it like a root password. Rotate it with:"
        echo "#   sudo $0 --rotate"
        echo "CONTROL_PANEL_ENABLED=${enabled}"
        echo "CONTROL_PANEL_TOKEN=\"${token}\""
        echo "CONTROL_PANEL_BIND=\"${bind}\""
        echo "CONTROL_PANEL_PORT=${port}"
    } > "$CONF_FILE"
    chmod 600 "$CONF_FILE"
    if [[ "${EUID}" -eq 0 ]]; then
        chown root:root "$CONF_FILE"
    fi
}

generate_token() {
    command -v openssl >/dev/null 2>&1 || die "openssl not found -- required to generate a secure admin token."
    openssl rand -hex 32
}

print_token_once() {
    local token="$1"
    echo
    echo "================================================================"
    echo " Admin token (shown ONCE -- save it somewhere safe now):"
    echo
    echo "   ${token}"
    echo
    echo " Use it as:  Authorization: Bearer ${token}"
    echo " Rotate any time with:  sudo $0 --rotate"
    echo "================================================================"
    echo
}

install_systemd_unit() {
    [[ "$NO_SYSTEMD" -eq 1 ]] && { log "Skipping systemd unit install (--no-systemd)."; return 0; }
    if [[ "${EUID}" -ne 0 ]]; then
        warn "Not root -- skipping systemd unit install. Run control-panel.py manually, or re-run this as root."
        return 0
    fi
    command -v systemctl >/dev/null 2>&1 || { warn "systemctl not found -- skipping unit install."; return 0; }

    cat > "$UNIT_FILE" << EOF
[Unit]
Description=Game Server Platform - Web Control Panel
After=network.target

[Service]
Type=simple
# Runs as root: the control panel's own action script
# (control-panel-instance-action.sh) starts/stops systemd units, which is
# a privileged operation -- this mirrors the trust level this platform's
# existing stop-instance.sh / restart-instance.sh already require of
# whoever runs them by hand (both explicitly demand sudo/root today). See
# control-panel.py's module docstring for the token-based auth model that
# guards every request reaching that privileged action from the network.
User=root
ExecStart=/usr/bin/env python3 ${SCRIPTS_DIR}/control-panel.py --conf ${CONF_FILE}
Restart=on-failure
RestartSec=5
NoNewPrivileges=false

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
    systemctl enable --now gameserver-control-panel.service
    log "systemd unit installed and started: gameserver-control-panel.service"
}

stop_systemd_unit() {
    [[ "$NO_SYSTEMD" -eq 1 ]] && return 0
    command -v systemctl >/dev/null 2>&1 || return 0
    systemctl disable --now gameserver-control-panel.service 2>/dev/null || true
}

do_enable() {
    read_current_conf
    local token
    token="$(generate_token)"
    write_conf "1" "$token" "$BIND" "$PORT"
    log "Control panel ENABLED. Bind: ${BIND}:${PORT}. Config: ${CONF_FILE}"
    print_token_once "$token"
    install_systemd_unit
}

do_disable() {
    read_current_conf
    if [[ ! -f "$CONF_FILE" ]]; then
        log "Control panel was never configured -- nothing to disable."
        return 0
    fi
    write_conf "0" "$CUR_TOKEN" "$CUR_BIND" "$CUR_PORT"
    log "Control panel DISABLED. The existing token is kept in the config file but is now inert (every action request will be refused) until --enable or --rotate is run again."
    stop_systemd_unit
}

do_rotate() {
    read_current_conf
    local token
    token="$(generate_token)"
    local enabled="${CUR_ENABLED}"
    [[ "$enabled" == "1" ]] || enabled="1"
    write_conf "$enabled" "$token" "$CUR_BIND" "$CUR_PORT"
    log "Token ROTATED. Any client using the old token will now get 401 immediately."
    print_token_once "$token"
    if [[ "$NO_SYSTEMD" -ne 1 && "${EUID}" -eq 0 ]] && command -v systemctl >/dev/null 2>&1; then
        systemctl restart gameserver-control-panel.service 2>/dev/null || true
    fi
}

case "$MODE" in
    enable)
        require_root_unless_test "--enable"
        do_enable
        ;;
    disable)
        require_root_unless_test "--disable"
        do_disable
        ;;
    rotate)
        require_root_unless_test "--rotate"
        do_rotate
        ;;
    "")
        echo "This turns on a READ-WRITE web control panel: anyone who obtains the admin"
        echo "token gains the ability to start/stop/restart your game server instances"
        echo "over HTTP. It is OFF by default and stays off unless you explicitly enable it."
        echo
        if [[ "$ASSUME_YES" -eq 1 ]]; then
            answer="n"
        else
            read -r -p "Enable the read-write web control panel now? [y/N]: " answer || answer="n"
        fi
        if [[ "${answer,,}" =~ ^y ]]; then
            require_root_unless_test "--enable"
            do_enable
        else
            echo "Not enabled. Nothing was changed. Re-run with --enable any time."
        fi
        ;;
esac
